
<script type="text/javascript">
	$j('document').ready(function() {
		$j( "#addproductsassoc" ).val("Also add to cart products:");
<?php  if(Mage::registry('page_need_reload')): ?>
location.reload();
<?php endif  ?>
});
</script>
<h1><?php //echo var_dump(Mage::register('page_need_reload', true)); die();?></h1>
<?php if($this->getItemCount()): ?>
<h1>Add crossccell products to cart</h1>
<div class="col-main">
<form id="productsassocform" action="<?php echo $this->getUrl("checkout/cart/"); ?>" method="post">
<?php echo $this->getBlockHtml('formkey') ?>
<input id="productassocids" value="" name="idsinput" class="idsinput"/>
<input id="addproductsassoc" type="submit"  class="button btn-cart"/>
</form>
    <?php foreach($this->getItems() as $_item): ?>
		<li>
			<div>
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(210); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
            </a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                <?php $this->getPriceHtml($_item, true) ?>              
            </div>
            <div class="div-table-col">
			<div>
				<input type="checkbox" name="<?php  echo $_item->getName()?>" value="<?php echo $_item->getId()?>" class="productassoccheckbox" onclick="updateProducts()"/>
            <div>
        </li>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<script type="text/javascript">
function updateProducts(){
	var checkboxes = $j( ".productassoccheckbox" );
	var button = $j( "#addproductsassoc" );
	var buttonText = $j( "#productsassoc" ).text();
	var productsText = "";
	button.text("");
	var productsIds = "";
	for(i=0; i< checkboxes.length; i++)
	{
		if(checkboxes[i].checked)
		{
			 productsText += " ";
			 productsText += checkboxes[i].name;
			 productsText += ", ";
			 productsIds += checkboxes[i].value;
			 productsIds += '|';
		}
	}
	button.val("Also add to cart products:"+productsText);
	$j("#productassocids" ).val("");
	$j("#productassocids" ).val(productsIds);	
}
</script>
